### PR TITLE
Vendor: PUBG-ify for Gaming High speed fps

### PR DESCRIPTION
**Pull request by gituser01mtk**
* By Default ROM slow so lets PUBG-ify

### CODE REVIEW

**Comment by Maitreya29** [comment]
Just did build and I can confirm things work better

**Comment by NitroVenom** [comment]
> Just did build and I can confirm things work better

Me too

**Comment by techyminati** [comment]
> Just did build and I can confirm things work better

Yeah , performance increased drastically !

**Comment by sarthakroy2002** [comment]
IT IS FUCKING GREAT... JOEY WILL PICK IT SOON..EVOX GAMING SOR

**Review by gpri989 — APPROVED** [review]

**Pull request closed without merging**
